### PR TITLE
About Azure SignalR Metric

### PR DESCRIPTION
**Pull request by RikaEndo0**
Japanese was changed to match the English version.

With Incident reactivation: [PROD] Sev 4: ID 108113477: [CSS] - [PRO] [the aggregation type of “System Errors” and “User Errors” Metric ]

to use Average for UserErrors and SystemErrors (Microsoft.SignalR/SignalR)

### CODE REVIEW

**Comment by v-cchen** [comment]
Hello, @RikaEndo0 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by RikaEndo0** [comment]
Hello, v-cchen ,  Microsoft C&E Localization Team、

Could you please let me know if you have any updates on fix the documents?
Or when do you think you will be done?

Regard,
Rika

**Comment by RikaEndo0** [comment]
HI Rika,
We will check and get back to you asap.

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 2:21 PM
To: MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com>; Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com>
Cc: Mention <mention@noreply.github.com>; Arthur Yasinski <Arthur.Yasinski@microsoft.com>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hello, v-cchen ,  Microsoft C&E Localization Team、

Could you please let me know if you have any updates on fix the documents?
Or when do you think you will be done?

Regard,
Rika

**Comment by v-cchen** [comment]
Hello, @RikaEndo0,

Thank you for your feedback and suggestion. 
 
The English source file has been updated recently. Your feedback will be considered when localizing the new version.

Many thanks for your contribution.

Kind regards, 
Microsoft C&E Localization Team

**Comment by RikaEndo0** [comment]
Hi Champ , Arthur,

I have confirmed that this request has been closed, but the document has not yet been updated.
My premier customers are asking when the documents will fix. Could you please tell me when you plan to fix the document? or please let me know if there are other appropriate consultations.


[cid:image002.png@01D4E975.10F4EF80]

Regard,
Rika

From: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com>
Sent: Tuesday, April 2, 2019 4:07 PM
To: Rika Endo <rikaendo@microsoft.com>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Arthur Yasinski <Arthur.Yasinski@microsoft.com>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

HI Rika,
We will check and get back to you asap.

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 2:21 PM
To: MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>; Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hello, v-cchen ,  Microsoft C&E Localization Team、

Could you please let me know if you have any updates on fix the documents?
Or when do you think you will be done?

Regard,
Rika

**Comment by RikaEndo0** [comment]
Hi Rika,
The new version of file is in translation, and updated doc would be reflected on 04/05.
Thank you,

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 4:02 PM
To: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com>; Arthur Yasinski <Arthur.Yasinski@microsoft.com>
Cc: Mention <mention@noreply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; CSS Japan Business - DSI Support <jpdsisp@microsoft.com>; Zhidi Shang <zhshang@microsoft.com>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hi Champ , Arthur,

I have confirmed that this request has been closed, but the document has not yet been updated.
My premier customers are asking when the documents will fix. Could you please tell me when you plan to fix the document? or please let me know if there are other appropriate consultations.


[cid:image002.png@01D4E96E.1DFCD410]

Regard,
Rika

From: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>
Sent: Tuesday, April 2, 2019 4:07 PM
To: Rika Endo <rikaendo@microsoft.com<mailto:rikaendo@microsoft.com>>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

HI Rika,
We will check and get back to you asap.

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 2:21 PM
To: MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>; Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hello, v-cchen ,  Microsoft C&E Localization Team、

Could you please let me know if you have any updates on fix the documents?
Or when do you think you will be done?

Regard,
Rika

**Comment by RikaEndo0** [comment]
Hi Champ, thank you for your reply. We look forward to.

Regard,
Rika

From: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com>
Sent: Tuesday, April 2, 2019 5:07 PM
To: Rika Endo <rikaendo@microsoft.com>; Arthur Yasinski <Arthur.Yasinski@microsoft.com>
Cc: Mention <mention@noreply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; CSS Japan Business - DSI Support <jpdsisp@microsoft.com>; Zhidi Shang <zhshang@microsoft.com>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hi Rika,
The new version of file is in translation, and updated doc would be reflected on 04/05.
Thank you,

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 4:02 PM
To: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; CSS Japan Business - DSI Support <jpdsisp@microsoft.com<mailto:jpdsisp@microsoft.com>>; Zhidi Shang <zhshang@microsoft.com<mailto:zhshang@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hi Champ , Arthur,

I have confirmed that this request has been closed, but the document has not yet been updated.
My premier customers are asking when the documents will fix. Could you please tell me when you plan to fix the document? or please let me know if there are other appropriate consultations.


[cid:image001.png@01D4E976.DE73A2C0]

Regard,
Rika

From: Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>
Sent: Tuesday, April 2, 2019 4:07 PM
To: Rika Endo <rikaendo@microsoft.com<mailto:rikaendo@microsoft.com>>; MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

HI Rika,
We will check and get back to you asap.

Best Regards,
Champ

From: Rika Endo
Sent: Tuesday, April 2, 2019 2:21 PM
To: MicrosoftDocs/azure-docs.ja-jp <reply@reply.github.com>; MicrosoftDocs/azure-docs.ja-jp <azure-docs.ja-jp@noreply.github.com<mailto:azure-docs.ja-jp@noreply.github.com>>; Champ Chen (Moravia IT s.r.o.) <v-cchen@microsoft.com<mailto:v-cchen@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Arthur Yasinski <Arthur.Yasinski@microsoft.com<mailto:Arthur.Yasinski@microsoft.com>>
Subject: RE: [MicrosoftDocs/azure-docs.ja-jp] About Azure SignalR Metric (#2245)

Hello, v-cchen ,  Microsoft C&E Localization Team、

Could you please let me know if you have any updates on fix the documents?
Or when do you think you will be done?

Regard,
Rika

**Pull request closed without merging**
