### PR TITLE
Update document-formats-naming-convention.md

### PR DESCRIPTION
**Pull request by soshogoh**
1. access https://portal.customtranslator.azure.ai
2. Create any workspace and projects.
3. On Documents, Select [Upload files] to upload any parallel data. browse any txt file which file name include Japanese characters such as 日本語.txt, and Upload.  then the following error message will displayed. the upload will be failed. If use the english file name, the upload will be sucessful.

Something went wrong
An unknown error occured.Please try again later.

### CODE REVIEW

**Comment by soshogoh** [comment]
Suggest to fix Custom Translator Upload file name which does not support Japanese chracters.
image
image

**Comment by LisandroSu** [comment]
Hello @soshogoh ,
		
Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly.

Thank you for your time and support.
Microsoft C&E Localization Team

**Comment by soshogoh** [comment]
Thanks Lisandro for your reply.
I am looking forward to be hearing you soon.

Best Regards
Munemasa

**Comment by v-radelg** [comment]
@soshogoh :
Thank you for your feedback and suggestion!
We agree with your suggestions, and we will include them into the next article update release.
see https://github.com/MicrosoftDocs/azure-docs-pr/pull/69154
Thank you for your time and support. 
Microsoft C&E Localization Team

**Pull request merged**
