### PR TITLE
sso url change request

### PR DESCRIPTION
**Pull request by KIchiyanagi**
SSO URL and support process are updated

### CODE REVIEW

**Comment by gosali** [comment]
Hi @KIchiyanag , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by KIchiyanagi** [comment]
Hi, gosali,
How about this pull request going?
Please tell me if any additional information required.

**Comment by jeevansd** [comment]
#sign-off

**Comment by gosali** [comment]
@KIchiyanagi : Thank you for your feedback and suggestion! 
  
The English source file is updated, your feedback is considered when we localize the new version. We will publish the new version of this article very soon. 
  
Microsoft C&E Localization Team

**Pull request closed without merging**
