### PR TITLE
Create Custom-Translator-Documentation.md

### PR DESCRIPTION
**Pull request by hatsunea**

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @hatsunea  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hello @hatsunea , thank for your contribution. 

We are currently reviewing it with the Core Team.
See issue: https://github.com/MicrosoftDocs/azure-docs/issues/13160

We will communicate the decision taken accordingly. 
Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hello @hatsunea , thank for your contribution.

We are currently reviewing it with the Core Team.
See issue: MicrosoftDocs/azure-docs#13160

We will communicate the decision taken accordingly.
Thanks for your time and support.
CC: @Sara-Nicolini 
Kind regards, Microsoft C&E Localization Team

**Comment by erhopf** [comment]
#please-close

@hatsunea - Unfortunately, this PR doesn't meet our contribution requirements. However, we understand that there are gaps in our current documentation and have plans to release updated Custom Translator content after Ignite.

**Pull request closed without merging**
