### PR TITLE
Brand name and support process update

### PR DESCRIPTION
**Pull request by KIchiyanagi**
There are many mistakes in this document.
1. App name is "LINE WORKS", not "WORKS MOBILE"
2. Support DL is not monitored now. please delete that paragraph.

### CODE REVIEW

**Comment by gosali** [comment]
Hi @KIchiyanagi , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by jeevansd** [comment]
This article does not require any next steps, so I have not added it. SaaS app tutorials are not TOC integrated.
Our toc is here: https://docs.microsoft.com/en-us/azure/active-directory/active-directory-saas-tutorial-list
#sign-off

**Comment by KIchiyanagi** [comment]
@jeevansd 
Can you share me a way to integrate TOC?
Our support team are seriously confusing due to a misleading process in this article.

**Comment by jeevansd** [comment]
@KIchiyanagi Our TOC is here https://docs.microsoft.com/azure/active-directory/active-directory-saas-tutorial-list

**Comment by KIchiyanagi** [comment]
@jeevansd 
Our app seems to be integrated In this list, but an error in the app name.
"WORKS MOBILE" is an old brand name of our service.

**Comment by v-radelg** [comment]
@KIchiyanagi : Thank you for your feedback and suggestion! 

The feedback is considered. We will tune part of  your feedback in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
		
Microsoft C&E Localization Team

**Pull request merged**
