### PR TITLE
Delete unnecessary brackets

### PR DESCRIPTION
**Pull request by changeworld**

### CODE REVIEW

**Comment by LisandroSu** [comment]
Hello, @changeworld 

Thank for your contribution. We are currently reviewing it. We will communicate the decision taken  accordingly. 
 
Thanks for your time and support on this.

Kind regards,

Microsoft C&E Localization Team

**Comment by yzheng-msft** [comment]
#sign-off

**Comment by yzheng-msft** [comment]
#sign-off

**Comment by v-radelg** [comment]
Hello, @changeworld  ,  Thank you for your feedback and suggestion. 

The English source file has been updated recently. Your feedback was considered when localizing the new version.  

Many thanks for your contribution.  

Kind regards,  Microsoft C&E Localization Team

**Pull request closed without merging**
