### PR TITLE
Update azure-resource-manager/resource-group-template-functions-array.md

### PR DESCRIPTION
**Pull request by kuniteru**
don't translate function name 'intersection'

### CODE REVIEW

**Comment by kuniteru** [comment]
I'm sorry, I had mistake in this thread.
I wanted to pull request to other branch to second file(vpn-gateway-forced-tunneling-rm.md).

**Comment by gosali** [comment]
Hi @kuniteru, we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
Hi @kuniteru, we are still in discussing, will update the decision later soon.

Thanks for your support,
Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@kuniteru , Thank you for your feedback and suggestion! 

The suggestion will be merged to the production, we will re-release this articles in the next loc release round.

Microsoft C&E Localization Team

**Pull request merged**
